### ISSUE TITLE
数据集问题

### ISSUE THREAD

**Issue by Tanghaiyang4013** [woldier/EEGDiR#1]
你好，我想问一下，数据集中的SS-EOG是指什么，数据集中的数据都是经过y=x+λn随机处理了的吗？

**Comment by woldier** [comment]
Hi, TangHaiYang:
 为了在更多的数据集上验证本文模型的性能, 我们使用了其他数据集做模型性能验证. SS-EOG 是指的"A semi-simulated eeg/eog dataset for the comparison of eog artifact rejection techniques"一文中提出的数据集. 
 这个数据集也同样的进行了y=x+λn的随机处理. 不过我们目前尚未将最新版本的paper 上传至arxiv. 后续会在arxiv更新这部分实验.
此致,
    woldier

**Comment by woldier** [comment]
Hi, TangHaiYang:
    现在, 我们已在arxiv上更新了最新版本, https://arxiv.org/abs/2404.15289.  @Tanghaiyang4013
此致, 
    woldier

**Comment by Tanghaiyang4013** [comment]
谢谢作者，感谢回复。

**Comment by woldier** [comment]
Hi, TangHaiYang:
    没有其他问题的话, 我就将此issue close了哈. @Tanghaiyang4013 
此致,
woldier

**Comment by woldier** [comment]
问题已经解决
